/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyFirstGradle;

import org.junit.Test;
import java.util.Scanner;
import java.io.FileWriter;
import java.io.IOException;
import static org.junit.Assert.*;

public class LibraryTest {
	
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
